### ISSUE TITLE
Make sure that test can be run automatically.

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#16]
Currently the test is run automatically when you run docker-compose up in the base folder of the ostelco-core project.

But what we would like is an end to end test that can be triggered that would 
  * run docker-compose up
  * expose the results from the test
  * do docker-compose down

**Comment by vihangpatil** [comment]
Updated the documentation - TEST.md
This will automatically stop all containers at end of the test
`docker-compose up --build --abort-on-container-exit`

Closing this issue.
