### ISSUE TITLE
[OCS] BundleId missing in PrimeEvent for CCR

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#220]
https://github.com/ostelco/ostelco-core/blob/develop/ocs/src/main/kotlin/org/ostelco/prime/events/EventProcessor.kt#L34

requires a bundle id. But it is not set in

https://github.com/ostelco/ostelco-core/blob/develop/ocs/src/main/kotlin/org/ostelco/prime/ocs/OcsState.kt#L45

**Comment by vihangpatil** [comment]
Fixed in prime-1.11.0
