### ISSUE TITLE
Remove hardcoded product Ids used in prime, move them to configutration.

### ISSUE THREAD

**Issue by prasanthu** [ostelco/ostelco-core#386]
e.g.
```
neo4j-store/src/main/kotlin/org/ostelco/prime/storage/graph/Neo4jStore.kt
                                }
                            }.bind()
                    // Give 100 MB as free initial balance
                    var productId: String = "100MB_FREE_ON_JOINING"
```

@la3lma says : This is a business rule that is now encoded as code. That is in general an anti pattern, at lest update the comment to contain an XXX or TODO so that it is easer to pick up this thing and amend later.

I would prefer this particular function to be added either via configuration or via a separate API, but that's not required for this PR. This is technical debt for sure.

**Comment by vihangpatil** [comment]
This is resolved by this PR: https://github.com/ostelco/ostelco-core/pull/688
