### ISSUE TITLE
[Question] Does ES2+ client usable with commercial SMDP+?

### ISSUE THREAD

**Issue by Gigithecode** [ostelco/ostelco-core#649]
Hello,

Does ES2+ client usable out of the box with commercial GSMA grade SMDP+?
We're very excited to test it with Gemalto/THALES SMDP+ server...

Thank you for your work!
Guillaume Ballet

**Comment by la3lma** [comment]
Hi Guillaume

Saw your post just now, hence the late reply.  Yes it does work with commercial ES2+.  The implementation is strictly (as strict as we could make it) in accordance with the GSMA protocol.   We have tested it against a commercial Idemia SM-DP+ and it working fine.  There are vendor specific extensions to the ES2+ protocols  but we have stayed away from those in the public code.

So, yes, it should work fine.  Also, the codebase is pretty extensible, and the license permits it, so you could make your own version that contains trade secrets  for vendor-specific extensions, should you need it.

I hope you found this useful.  I'll be happy to answer any questions you might have, and should you have any pull requests related to this code I will be happy to review and merge them into the codebase.

Best wishes



Bjørn Remseth

**Comment by Gigithecode** [comment]
Hello Bjørn,

Thank you very much for your kind answer.
Our goal is to make Ostelco work with Thales/Gemalto commercial SMDP+ 
server. We're going to have an access to Gemalto's such a server.

We would be happy to share our results with you!

For now we're far away to make Ostelco work and even compile without errors.
Perhaps do you have some idea about the following errors?

We also have a concern with gcloud ; i'm not used at all with it... do 
you have a comprehensive howto for getting the necessary cloud resources 
on it? (for now I cannot run gradle deploy or test because I lack the 
necessary gcloud resources)

Last but not least we've no idea how to run the SMDP+ client. Can you 
help us on this matter?

Thank you very much for your help and for your hard work!

Guillaume Ballet

------------------------

gradle jar

....

 > Task :ekyc:compileKotlin FAILED
Cache entries evicted. In-memory cache of 
/home/gigi/.gradle/caches/journal-1/file-access.bin: Size{400} 
MaxSize{400}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, 
loadExceptionCount=0, totalLoadTime=0, evictionCount=2161}
Performance may suffer from in-memory cache misses. Increase max heap 
size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of 
/home/gigi/.gradle/caches/journal-1/file-access.bin: Size{400} 
MaxSize{400}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, 
loadExceptionCount=0, totalLoadTime=0, evictionCount=2163}
Performance may suffer from in-memory cache misses. Increase max heap 
size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of 
/home/gigi/.gradle/caches/journal-1/file-access.bin: Size{400} 
MaxSize{400}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, 
loadExceptionCount=0, totalLoadTime=0, evictionCount=2164}
Performance may suffer from in-memory cache misses. Increase max heap 
size of Gradle build process to reduce cache misses.
Cache entries evicted. In-memory cache of 
/home/gigi/.gradle/caches/journal-1/file-access.bin: Size{400} 
MaxSize{400}, CacheStats{hitCount=0, missCount=0, loadSuccessCount=0, 
loadExceptionCount=0, totalLoadTime=0, evictionCount=2162}
Performance may suffer from in-memory cache misses. Increase max heap 
size of Gradle build process to reduce cache misses.
Caching disabled for task ':ekyc:compileKotlin' because:
   Build cache is disabled
Task ':ekyc:compileKotlin' is not up-to-date because:
   Task has failed previously.
All input files are considered out-of-date for incremental task 
':ekyc:compileKotlin'.
file or directory '/home/gigi/ostelco-core/ekyc/src/main/java', not found
file or directory '/home/gigi/ostelco-core/ekyc/src/main/java', not found
Using Kotlin/JVM incremental compilation
Options for KOTLIN DAEMON: 
IncrementalCompilationOptions(super=CompilationOptions(compilerMode=INCREMENTAL_COMPILER, 
targetPlatform=JVM, reportCategories=[0], reportSeverity=2, 
requestedCompilationResults=[0]), areFileChangesKnown=false, 
modifiedFiles=null, deletedFiles=null, 
workingDir=/home/gigi/ostelco-core/ekyc/build/kotlin/compileKotlin, 
multiModuleICSettings=MultiModuleICSettings(buildHistoryFile=/home/gigi/ostelco-core/ekyc/build/kotlin/compileKotlin/build-history.bin, 
useModuleDetection=false), 
usePreciseJavaTracking=trueoutputFiles=[/home/gigi/ostelco-core/ekyc/build/classes/kotlin/main, 
/home/gigi/ostelco-core/ekyc/build/kotlin/compileKotlin])
e: 
/home/gigi/ostelco-core/ekyc/src/main/kotlin/org/ostelco/prime/ekyc/myinfo/MyInfoClient.kt: 
(98, 116): Type mismatch: inferred type is Charset! but String! was expected
e: 
/home/gigi/ostelco-core/ekyc/src/main/kotlin/org/ostelco/prime/ekyc/myinfo/MyInfoClient.kt: 
(191, 19): Unresolved reference: readAllBytes
e: 
/home/gigi/ostelco-core/ekyc/src/main/kotlin/org/ostelco/prime/ekyc/myinfo/MyInfoClient.kt: 
(192, 32): Unresolved reference: it
e: 
/home/gigi/ostelco-core/ekyc/src/main/kotlin/org/ostelco/prime/ekyc/myinfo/MyInfoClient.kt: 
(194, 65): Unresolved reference: it
:ekyc:compileKotlin (Thread[Execution worker for ':',5,main]) completed. 
Took 0.312 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':ekyc:compileKotlin'.
 > Compilation error. See log for more details

...

gigi@clevo:~/ostelco-core$ uname -a
Linux clevo.gigi.edu 4.13.0-16-generic #19-Ubuntu SMP Wed Oct 11 
18:35:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
gigi@clevo:~/ostelco-core$ lsb_release -a
LSB Version: 
core-9.20170808ubuntu1-noarch:printing-9.20170808ubuntu1-noarch:security-9.20170808ubuntu1-noarch
Distributor ID:    Ubuntu
Description:    Ubuntu 18.04.2 LTS
Release:    18.04
Codename:    bionic
gigi@clevo:~/ostelco-core$ gradle -v
Picked up JAVA_TOOL_OPTIONS: 
-Dsun.security.smartcardio.library=/usr/local/lib/libpcsclite.so.1.0.0

------------------------------------------------------------
Gradle 5.4.1
------------------------------------------------------------

Build time:   2019-04-26 08:14:42 UTC
Revision:     261d171646b36a6a28d5a19a69676cd098a4c19d

Kotlin:       1.3.21
Groovy:       2.5.4
Ant:          Apache Ant(TM) version 1.9.13 compiled on July 10 2018
JVM:          1.8.0_212 (Oracle Corporation 25.212-b03)
OS:           Linux 4.13.0-16-generic amd64

gigi@clevo:~/ostelco-core$ gcloud  -v
Google Cloud SDK 249.0.0
alpha 2019.05.31
beta 2019.05.31
bq 2.0.43
core 2019.05.31
gsutil 4.38
kubectl 2019.05.31

--------------------------------------------

Le 06/06/2019 à 14:41, Bjørn Remseth a écrit :

**Comment by la3lma** [comment]
In order to compile all, the current convenience script that is being used (by me :-) ) is build-all.go.   It should build everything and run a set of "acceptance tests".   To make it work you need:

*  A Stripe account.  Only test credentials are used.
*  An account in the Google cloud solution, and an account set up there to store things to during the acceptance test.   The setup of this account is badly documented :-(. Thank you for reminding me about that.  I will discuss this with my colleagues and get back to you with a detailed answer. 

However, if you're only interested in using the ES2+ client, then you don't need all that.   Just typing "./gradlew build" should do the trick. The library will then be built, among with everything else, but none of the tests requiring external login credentials will be needed.  Would it be helpful for you if we separated the ES2+ protocol code  into a separate library that you could depend on without depending on everything else?  It's certainly doable, but not something we've done so far, and if it would help you we will give it serious consideration.

May I ask  what your use case is?

Best wishes 

Bjørn

**Comment by Gigithecode** [comment]
Hello Bjørn,

Thank you for your mail. We still are stuck compiling (./gradlew build) 
because some tests cannot fulfilled - it seems that a prerequisite is a 
Strive (or Google prime?) account... (Missing Firebase Credentials file: 
config/prime-service-account.json)

Do you have an even minimal documentation setting up the cloud accounts, 
we're a little bit lost in this matter.

We cannot find any reference to es2plus inside the following generated 
libraries ;

For example the Es2PlusClient classe isn't found inside.

./app-notifier/build/libs/app-notifier-1.0.0-SNAPSHOT.jar
./bq-metrics-extractor/build/libs/bq-metrics-extractor-2.1.0.jar
./firebase-extensions/build/libs/firebase-extensions-1.0.0-SNAPSHOT.jar
./model/build/libs/model-1.0.0-SNAPSHOT.jar
./prime-customer-api/build/swagger-code-java-client/gradle/wrapper/gradle-wrapper.jar
./prime-customer-api/build/libs/prime-customer-api-1.0.0-SNAPSHOT.jar
./data-store/build/libs/data-store-1.0.0-SNAPSHOT.jar
./customer-endpoint/build/libs/customer-endpoint-1.0.0-SNAPSHOT.jar
./dataflow-pipelines/build/libs/dataflow-pipelines-1.0.0-SNAPSHOT.jar
./build/libs/ostelco-core-1.0.0-SNAPSHOT.jar
./diameter-test/build/libs/diameter-test-1.0.0-SNAPSHOT.jar
./admin-api/build/tmp/expandedArchives/org.jacoco.agent-0.8.2.jar_2aca8b620b19ecd063f63feff8caaa38/jacocoagent.jar
./admin-api/build/libs/admin-api-1.0.0-SNAPSHOT.jar
./auth-server/build/tmp/expandedArchives/org.jacoco.agent-0.8.2.jar_2aca8b620b19ecd063f63feff8caaa38/jacocoagent.jar
./auth-server/build/libs/auth-server-1.0.0-SNAPSHOT.jar
./auth-server/build/libs/auth-server-uber.jar
./prime-modules/build/libs/prime-modules-1.0.0-SNAPSHOT.jar
./analytics-module/build/libs/analytics-module-1.0.0-SNAPSHOT.jar
./diameter-ha/build/libs/diameter-ha-1.0.0-SNAPSHOT.jar
./jersey/build/libs/jersey-1.0.0-SNAPSHOT.jar
./diameter-stack/build/libs/diameter-stack-1.0.0-SNAPSHOT.jar
./ocs-grpc-api/build/libs/ocs-grpc-api-1.0.0-SNAPSHOT.jar
./analytics-grpc-api/build/libs/analytics-grpc-api-1.0.0-SNAPSHOT.jar
./gradle/wrapper/gradle-wrapper.jar
./acceptance-tests/build/libs/acceptance-tests-uber.jar
./acceptance-tests/build/libs/acceptance-tests-1.0.0-SNAPSHOT.jar

gigi@clevo:~/ostelco-core$ grep -ri es2+
Fichier binaire .git/index correspondant
sim-administration/sm-dp-plus/src/main/java/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* to serve a few simple ES2+ commands, and to do so consistently, and to
sim-administration/sm-dp-plus/src/main/java/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* report back to the sim administration application via ES2+ callback, as to
sim-administration/sm-dp-plus/src/main/java/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* ES2+ services
sim-administration/sm-dp-plus/src/test/resources/config.yml: 
description: Test fixture simulating ES2+ interactions of an SM-DP+
sim-administration/sm-dp-plus/src/test/java/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* to serve a few simple ES2+ commands, and to do so consistently, and to
sim-administration/sm-dp-plus/src/test/java/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* report back to the sim administration application via ES2+ callback, as to
sim-administration/sm-dp-plus/src/test/java/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* ES2+ services
sim-administration/simmanager/src/main/kotlin/org/ostelco/simcards/inventory/SimInventoryCallbackService.kt: 
* ES2+ callbacks handling.
sim-administration/simmanager/src/main/kotlin/org/ostelco/simcards/inventory/SimInventoryDAO.kt:/* 
ES2+ interface description - GSMA states forward transition. */
sim-administration/simmanager/src/main/kotlin/org/ostelco/simcards/inventory/SimInventoryDAO.kt: 
/* ES2+ protocol - between SM-DP+ servcie and backend. */
sim-administration/simmanager/src/integration-test/resources/sm-dp-plus.yaml: 
description: Test fixture simulating ES2+ interactions of a SM-DP+
sim-administration/simmanager/src/integration-test/kotlin/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* to serve a few simple ES2+ commands, and to do so consistently, and to
sim-administration/simmanager/src/integration-test/kotlin/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* report back to the sim administration application via ES2+ callback, as to
sim-administration/simmanager/src/integration-test/kotlin/org/ostelco/simcards/smdpplus/SmDpPlusApplication.kt: 
* ES2+ services
sim-administration/jersey-json-schema-validator/src/test/java/org/ostelco/jsonschema/TestJsonValidation.kt: 
val inputStream = 
this.javaClass.getResourceAsStream("/es2schemas/ES2+DownloadOrder-def.json")
sim-administration/ES2+.md:  of ES2+ interactions that can be used to 
check assumptions made
sim-administration/ES2+.md:  ES2+-conformant JSON that the resource is 
supposed to produce.
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusResources.kt: 
* Invoked when an exception is thrown when handling an ES2+ request.
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+DownloadOrder-def")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+DownloadOrder-response")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+ConfirmOrder-def")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+ConfirmOrder-response")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:// 
XXX CXHeck @JsonSchema("ES2+CancelOrder-def")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+HeaderOnly-response")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+ReleaseProfile-def")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusEntities.kt:@JsonSchema("ES2+HandleDownloadProgressInfo-def")
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusClient.kt: 
* the ES2+ protocol.
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusClient.kt: 
//       functioning & testable  ES2+ client.   Should be implemented 
using two different
sim-administration/es2plus4dropwizard/src/main/java/org/ostelco/sim/es2plus/Es2PlusClient.kt: 
* Thrown when something goes wrong with the ES2+ protocol.
sim-administration/es2plus4dropwizard/src/test/java/org/ostelco/sim/es2plus/EncryptedRemoteEs2ClientOnlyTest.kt: 
* ES2+ services
sim-administration/es2plus4dropwizard/src/test/java/org/ostelco/sim/es2plus/Es2plusApplication.kt: 
return "es2+ application"
sim-administration/ostelco-dropwizard-utils/src/test/java/PingPongApp.kt: 
* ES2+ services
sim-administration/README.md:* Return channel for ES2+
sim-administration/README.md:   * Figure out where we want to place the 
return channel for ES2+
sim-administration/README.md:    done over ES2+ protocol.
sim-administration/README.md:  preserving authentication for incoming 
ES2+ callbacks.
Fichier binaire sim-administration/docs/SGP.23-v1.3.pdf correspondant

Yes, we definitively would be happy to get the ES2+ protocol in a 
separate library. To get some basic api documentation would be great 
too. It will be easier for our needs, but to compile and run Ostelco as 
it is remains interesting and something that we would like to do also.

The French Ministry of Interior have a deal with Thales/Gemalto about 
buying eUICC for our next gen Mission Critical PPDR LTE based (PCSTORM 
project, https://www.rrmediagroup.com/Features/FeaturesDetails/FID/919).

In this matter we need to communicate with Gemalto SM-DP+ servers for 
the eUICC provisionning.

Any help you can bring will be highly appreciated!

Kind regards.

Guillaume Ballet

...

 > Task :auth-server:integration
Caching disabled for task ':auth-server:integration' because:
   Build cache is disabled
Task ':auth-server:integration' is not up-to-date because:
   Task has failed previously.
Starting process 'Gradle Test Executor 2'. Working directory: 
/home/gigi/ostelco-core/auth-server Command: 
/usr/lib/jvm/java-8-openjdk-amd64/bin/java 
-Djava.security.manager=worker.org.gradle.process.internal.worker.child.BootstrapSecurityManager 
-Dorg.gradle.native=false 
-javaagent:build/tmp/expandedArchives/org.jacoco.agent-0.8.2.jar_2aca8b620b19ecd063f63feff8caaa38/jacocoagent.jar=destfile=build/jacoco/integration.exec,append=true,inclnolocationclasses=false,dumponexit=true,output=file,jmx=false 
-Xmx512m -Dfile.encoding=UTF-8 -Duser.country=FR -Duser.language=fr 
-Duser.variant -ea -cp 
/home/gigi/.gradle/caches/5.4.1/workerMain/gradle-worker.jar 
worker.org.gradle.process.internal.worker.GradleWorkerMain 'Gradle Test 
Executor 2'
Successfully started process 'Gradle Test Executor 2'
Picked up JAVA_TOOL_OPTIONS: 
-Dsun.security.smartcardio.library=/usr/local/lib/libpcsclite.so.1.0.0

org.ostelco.auth.AuthServerTest STANDARD_OUT
     INFO  [2019-06-14 14:56:12,577] 
io.dropwizard.server.DefaultServerFactory: Registering jersey handler 
with root path prefix: /
     INFO  [2019-06-14 14:56:12,581] 
io.dropwizard.server.DefaultServerFactory: Registering admin handler 
with root path prefix: /

Gradle Test Executor 2 finished executing tests.

 > Task :auth-server:integration FAILED

org.ostelco.auth.AuthServerTest > classMethod FAILED
     java.lang.RuntimeException: javax.naming.ConfigurationException: 
Missing Firebase Credentials file: config/prime-service-account.json

         Caused by:
         javax.naming.ConfigurationException: Missing Firebase 
Credentials file: config/prime-service-account.json

1 test completed, 1 failed
Finished generating test XML results (0.0 secs) into: 
/home/gigi/ostelco-core/auth-server/build/test-results/integration
Generating HTML test report...
Finished generating test html results (0.0 secs) into: 
/home/gigi/ostelco-core/auth-server/build/reports/tests/integration
:auth-server:integration (Thread[Execution worker for ':' Thread 
2,5,main]) completed. Took 2.744 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':auth-server:integration'.
 > There were failing tests. See the report at: 
file:///home/gigi/ostelco-core/auth-server/build/reports/tests/integration/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug 
option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 4s
83 actionable tasks: 1 executed, 82 up-to-date

Le 11/06/2019 à 23:21, Bjørn Remseth a écrit :

**Comment by vihangpatil** [comment]
Hi Guillaume,

Since you are interested only in the SMDP+ part, I suggest you can use `./gradlew :sim-administration:build`.
This will build projects under `sim-administration` only.
This will then work without Google Cloud / Firebase Service Account Credentials file.
The project `es2plus4dropwizard` library under `sim-administration` seems to be most relevant for your need.

Best Regards,
Vihang

**Comment by Gigithecode** [comment]
Hi Vihang,

The fact is es2plus4dropwizard classes and jar file wasn't generated until 
i found a way to compile the whole framework as well.
There was an issue in MyInfoClient.kt class setting val content = response...
and a few other errors in other classes as well.


Now I get GCP and Prime accounts and i can run the whole framework. There 
still is an error in a test because of a change in the Prime api.

My interrogation for now is how to setup and use the OSS/BSS.
Does it exist some kind of user manual?

We now got the certificates and SMDP+ endpoint socket from Gemalto, so we 
have everything to begin testing (at least in theory...)

Best regards.
Guillaume
