### ISSUE TITLE
[Prime] [OCSgw] make complete integration test

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#67]
The current integration test rely on Firebase to have users configured and have a balance.

We should make this run without Firebase. The test should be like:

    * Create a user
    * Top-up the balance for this user
    * Generate some CCR traffic

So that we can create tests where the user is running out of credit etc.

**Comment by vihangpatil** [comment]
Now, we have moved user info from Firebase to Neo4j. 
Acceptance tests now create a new user and use that user for testing.
I have skipped step 2, that is, top-up newly created user since the user will have a default balance of 100MB.
This is supported since prime-1.9.0.
