### ISSUE TITLE
[Prime] Create "CDR" for usage

### ISSUE THREAD

**Issue by mpeterss** [ostelco/ostelco-core#720]
There should be a way to get the usage per subscriber.

**Comment by cyriaquebrousse** [comment]
I need a bit more detail here. Where do we need this information?
In the PubSub => Dataflow => BigQuery flow, we collect consumption information per subscription, and it is possible to find out the customer identity from the subscription.

**Comment by mpeterss** [comment]
Yes, I thought this was already done in current PubSub => Dataflow => BigQuery flow. So I added you so we could close this as done :)
